'use client';

import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {clone as cloneSkeleton} from 'three/examples/jsm/utils/SkeletonUtils.js';
import RAPIER from '@dimforge/rapier3d-compat';

type Soldier={mesh:THREE.Object3D;team:'friendly'|'enemy';hp:number;timer:number;mixer?:THREE.AnimationMixer};
const SOLDIER_URL='https://threejs.org/examples/models/gltf/Soldier.glb';
export default function Game3D(){
 const ref=useRef<HTMLDivElement>(null);const [started,setStarted]=useState(false);const [health,setHealth]=useState(100);const [ammo,setAmmo]=useState(30);const [enemyCount,setEnemyCount]=useState(12);const [capture,setCapture]=useState(0);const [state,setState]=useState<'active'|'victory'|'defeat'>('active');
 useEffect(()=>{if(!started||!ref.current||state!=='active')return;let dead=false,raf=0;const scene=new THREE.Scene();scene.background=new THREE.Color(0x718080);scene.fog=new THREE.FogExp2(0x718080,.011);const camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,700);const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.domElement.className='game-canvas';ref.current.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xc9d8d8,0x283027,2));const sun=new THREE.DirectionalLight(0xffe0a4,3.4);sun.position.set(-80,120,50);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);const physics=new RAPIER.World({x:0,y:-18,z:0});const floor=physics.createRigidBody(RAPIER.RigidBodyDesc.fixed());physics.createCollider(RAPIER.ColliderDesc.cuboid(140,1,140).setTranslation(0,-1,0),floor);
 const terrain=new THREE.Mesh(new THREE.PlaneGeometry(280,280,64,64),new THREE.MeshStandardMaterial({color:0x536052,roughness:1}));terrain.rotation.x=-Math.PI/2;const ta=terrain.geometry.attributes.position;for(let i=0;i<ta.count;i++){const x=ta.getX(i),z=ta.getY(i);ta.setZ(i,Math.sin(x*.045)*2.5+Math.cos(z*.04)*2+Math.sin((x+z)*.07))}terrain.geometry.computeVertexNormals();terrain.receiveShadow=true;scene.add(terrain);const roadMat=new THREE.MeshStandardMaterial({color:0x393a36,roughness:1});for(const [x,z,w,d] of [[0,0,18,250],[45,-25,11,150],[-45,35,10,130]] as number[][]){const r=new THREE.Mesh(new THREE.BoxGeometry(w,.12,d),roadMat);r.position.set(x,.05,z);r.receiveShadow=true;scene.add(r)}
 const building=(x:number,z:number,w:number,d:number,h:number)=>{const g=new THREE.Group();const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color:0x595852,roughness:.9}));m.position.y=h/2;m.castShadow=true;m.receiveShadow=true;g.add(m);const roof=new THREE.Mesh(new THREE.BoxGeometry(w+1,.5,d+1),new THREE.MeshStandardMaterial({color:0x292d2b}));roof.position.y=h+.25;g.add(roof);g.position.set(x,0,z);scene.add(g);const b=physics.createRigidBody(RAPIER.RigidBodyDesc.fixed().setTranslation(x,h/2,z));physics.createCollider(RAPIER.ColliderDesc.cuboid(w/2,h/2,d/2),b)};building(40,-62,16,11,8);building(50,-48,9,8,6);building(-40,36,13,10,7);building(-56,52,10,8,5);
 const tower=new THREE.Group();const base=new THREE.Mesh(new THREE.CylinderGeometry(2.5,3,1,12),new THREE.MeshStandardMaterial({color:0x4a514b}));base.position.y=.5;tower.add(base);const mast=new THREE.Mesh(new THREE.CylinderGeometry(.22,.4,12,8),new THREE.MeshStandardMaterial({color:0x303634,metalness:.5}));mast.position.y=6;tower.add(mast);for(let i=0;i<3;i++){const q=new THREE.Mesh(new THREE.TorusGeometry(1.8-i*.35,.08,6,16),new THREE.MeshStandardMaterial({color:0x303634}));q.position.y=3.5+i*2.2;tower.add(q)}tower.position.set(40,0,-62);scene.add(tower);
 const tm=new THREE.MeshStandardMaterial({color:0x473729}),lm=new THREE.MeshStandardMaterial({color:0x2e4b37});for(let i=0;i<100;i++){const t=new THREE.Group(),b=new THREE.Mesh(new THREE.CylinderGeometry(.12,.2,2.5,6),tm),c=new THREE.Mesh(new THREE.ConeGeometry(1.6,4.2,7),lm);b.position.y=1.25;c.position.y=4;t.add(b,c);const ang=i*2.4,r=48+(i%8)*7;t.position.set(Math.cos(ang)*r,0,Math.sin(ang)*r);t.scale.setScalar(.7+(i%5)*.08);t.traverse(o=>{if((o as THREE.Mesh).isMesh)o.castShadow=true});scene.add(t)}
 const soldiers:Soldier[]=[];let template:THREE.Object3D|null=null;let clips:THREE.AnimationClip[]=[];let body:RAPIER.RigidBody|null=null;const spawn=(team:'friendly'|'enemy',x:number,z:number)=>{if(!template)return;const mesh=cloneSkeleton(template);mesh.scale.setScalar(1.25);mesh.position.set(x,0,z);mesh.traverse(o=>{if((o as THREE.Mesh).isMesh){o.castShadow=true;o.receiveShadow=true}});scene.add(mesh);const mixer=new THREE.AnimationMixer(mesh);const clip=clips.find(c=>/walk|run/i.test(c.name))||clips[0];if(clip)mixer.clipAction(clip).play();soldiers.push({mesh,team,hp:100,timer:Math.random()*2,mixer})};new GLTFLoader().load(SOLDIER_URL,g=>{if(dead)return;template=g.scene;clips=g.animations;body=physics.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(0,2,34).lockRotations());physics.createCollider(RAPIER.ColliderDesc.capsule(.75,.35),body);for(let i=0;i<6;i++)spawn('friendly',-10+i*3,28+(i%2)*3);for(let i=0;i<6;i++)spawn('friendly',-14+i*3,39+(i%2)*3);for(let i=0;i<12;i++)spawn('enemy',26+(i%4)*4,-20-Math.floor(i/4)*7)});
 const keys=new Set<string>(),vel=new THREE.Vector3(),ray=new THREE.Raycaster();let yaw=0,pitch=0,cool=0,capt=0;const key=(e:KeyboardEvent)=>{keys.add(e.code);if(e.code==='KeyR')setAmmo(30);if(e.code==='Escape')document.exitPointerLock?.()};const up=(e:KeyboardEvent)=>keys.delete(e.code);const move=(e:MouseEvent)=>{if(document.pointerLockElement===renderer.domElement){yaw-=e.movementX*.0022;pitch=THREE.MathUtils.clamp(pitch-e.movementY*.0018,-1.2,1.1)}};const fire=()=>{if(cool>0||ammo<=0)return;cool=.13;setAmmo(v=>Math.max(0,v-1));ray.setFromCamera(new THREE.Vector2(0,0),camera);const live=soldiers.filter(s=>s.team==='enemy'&&s.hp>0);const hit=ray.intersectObjects(live.map(s=>s.mesh),true)[0];if(hit){let o:any=hit.object;while(o&&!live.some(s=>s.mesh===o))o=o.parent;const s=live.find(s=>s.mesh===o);if(s){s.hp-=34;if(s.hp<=0){scene.remove(s.mesh);setEnemyCount(v=>Math.max(0,v-1))}}}};const click=()=>{if(document.pointerLockElement!==renderer.domElement)renderer.domElement.requestPointerLock();else fire()};addEventListener('keydown',key);addEventListener('keyup',up);renderer.domElement.addEventListener('mousemove',move);renderer.domElement.addEventListener('click',click);
 const clock=new THREE.Clock();const loop=()=>{if(dead)return;const dt=Math.min(clock.getDelta(),.05);physics.step();cool=Math.max(0,cool-dt);if(body){const f=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw)),r=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw));vel.set(0,0,0);if(keys.has('KeyW'))vel.add(f);if(keys.has('KeyS'))vel.sub(f);if(keys.has('KeyA'))vel.sub(r);if(keys.has('KeyD'))vel.add(r);if(vel.lengthSq())vel.normalize().multiplyScalar(keys.has('ShiftLeft')?11:5.5);body.setLinvel({x:vel.x,y:body.linvel().y,z:vel.z},true);const p=body.translation();camera.position.set(p.x,p.y+1.15,p.z);camera.rotation.order='YXZ';camera.rotation.set(pitch,yaw,0)}const pp=new THREE.Vector3(camera.position.x,0,camera.position.z);for(const s of soldiers){if(s.hp<=0)continue;s.mixer?.update(dt);s.timer-=dt;const p=s.mesh.position,d=p.distanceTo(pp);if(s.team==='enemy'){if(d<44){const q=pp.clone().sub(p);q.y=0;if(q.length()>12){q.normalize();p.addScaledVector(q,dt*1.5)}s.mesh.rotation.y=Math.atan2(q.x,q.z);if(d<30&&s.timer<=0){s.timer=1.5;setHealth(v=>{const n=Math.max(0,v-3);if(n===0)setState('defeat');return n})}}else p.x+=Math.sin(performance.now()/1800+s.mesh.id)*dt*.45}else{const q=pp.clone().sub(p);q.y=0;if(q.length()>5){q.normalize();p.addScaledVector(q,dt*1.8);s.mesh.rotation.y=Math.atan2(q.x,q.z)}}}const dist=pp.distanceTo(new THREE.Vector3(40,0,-62));capt=dist<14?Math.min(100,capt+dt*7):Math.max(0,capt-dt*2);setCapture(Math.round(capt));if(capt>=100&&enemyCount===0)setState('victory');renderer.render(scene,camera);raf=requestAnimationFrame(loop)};loop();const resize=()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)};addEventListener('resize',resize);return()=>{dead=true;cancelAnimationFrame(raf);removeEventListener('keydown',key);removeEventListener('keyup',up);removeEventListener('resize',resize);renderer.domElement.removeEventListener('mousemove',move);renderer.domElement.removeEventListener('click',click);renderer.dispose();physics.free();ref.current?.replaceChildren()}},[started,state]);
 if(!started)return <div className="game-shell"><div className="menu"><div className="menu-card fade"><div className="logo-small">DATAFOG STUDIOS PRESENTS</div><div className="logo">THE GREAT<em>INVASION</em></div><p className="menu-sub">OPERATION IRON GATE · NORTHERN FRONTIER · 06:42<br/>Lead Alpha and Bravo squads through a living 3D battlefield and secure the communications facility.</p><button className="begin" onClick={()=>setStarted(true)}>BEGIN OPERATION</button><div className="menu-note">REAL 3D · RIGGED CHARACTERS · AI · PHYSICS · TACTICAL COMBAT</div></div></div></div>;
 if(state!=='active')return <div className="game-shell"><div className="menu"><div className="menu-card fade"><div className="logo-small">{state==='victory'?'OPERATION COMPLETE':'OPERATION FAILED'}</div><div className="logo">{state==='victory'?'LINE':'THE LINE'}<em>{state==='victory'?'HELD':'BROKE'}</em></div><p className="menu-sub">{state==='victory'?'The communications facility is secure.':'The frontline has collapsed. Reorganize and redeploy.'}</p><button className="begin" onClick={()=>{setHealth(100);setAmmo(30);setEnemyCount(12);setCapture(0);setState('active')}}>REDEPLOY</button></div></div></div>;
 return <div className="game-shell"><div ref={ref}/><div className="hud"><div className="mission-card"><div className="mission-kicker">Operation Iron Gate</div><div className="mission-title">Hold The Line</div><p className="mission-copy">Advance through the valley and take the communications facility. Terrain, squads and enemy movement are simulated in real time.</p><div className="objective"><div className="objective-label">Primary objective</div><div className="objective-text">{capture>=100?'FACILITY CAPTURED — ELIMINATE REMAINING THREATS':'SECURE THE COMMUNICATIONS FACILITY'}</div></div></div><div className="top-right"><div className="status-chip">ENEMY <span>{enemyCount}</span></div><div className="status-chip">ALPHA <span>6</span></div><div className="status-chip">BRAVO <span>6</span></div></div><div className="compass">N · 06:42 · OVERCAST<div className="compass-line"/></div><div className="crosshair"/><div className="bottom-left"><div className="health-row"><div className="health-value">{health}</div><div className="health-label">COMBAT CONDITION</div></div><div className="bar"><i style={{width:health+'%'}}/></div><div className="ammo"><div className="ammo-main">{ammo}<small> / 30</small></div><div className="weapon">SERVICE RIFLE · SEMI AUTO</div></div></div><div className="bottom-center"><div className="capture"><div className="capture-title">COMMUNICATIONS FACILITY · {capture}%</div><div className="capture-bar"><i style={{width:capture+'%'}}/></div></div></div><div className="squad-panel"><div className="eyebrow">FIELD COMMAND</div><div className="squad-row"><b>ALPHA</b><span>6/6 · FOLLOW</span></div><div className="squad-row"><b>BRAVO</b><span>6/6 · ADVANCE</span></div><div className="squad-row"><b>ORDERS</b><span>WASD · SPRINT</span></div></div><div className="controls">CLICK TO LOCK MOUSE · WASD MOVE · SHIFT SPRINT · R RELOAD · CLICK FIRE · ESC RELEASE</div></div></div>}
